### ISSUE TITLE
attributeError: can't set attribute

### ISSUE THREAD

**Issue by LexieYang** [rehg-lab/lowshot-shapebias#4]
**Did anyone meet this issue and know how to solve it? Thank you in advance!**

Traceback (most recent call last):
  File "lssb/lowshot/train.py", line 112, in <module>
    main()
  File "lssb/lowshot/train.py", line 61, in main
    model = getattr(lowshot_models, hparams.model_type)(hparams)
  File "./lssb/lowshot/models/image_simpleshot_classifier.py", line 7, in __init__
    super().__init__(hparams)
  File "./lssb/lowshot/models/base_simpleshot_classifier.py", line 19, in __init__
    self.hparams = hparams
  File "/home/myang47/anaconda3/envs/ifsl_pytorch1.7.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 826, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

**Comment by LexieYang** [comment]
Sorry, I solve this issue after setting up the conda environment as the author suggested.
